[package]
name = "bagpiper"
version = "0.1.0"
edition = "2021"
authors = ["Avi Srivastava <avisrilab@gmail.com>"]
description = "A suite of tools for rapid analysis of PIP-seq data."
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/avisrilab/bagpiper"
homepage = "https://github.com/avisrilab/bagpiper"
keywords = ["single-cell", "RNA-seq"]
categories = ["command-line-utilities", "science"]

[lib]
name = "bagpiper"
path = "src/lib.rs"

[[bin]]
name = "bagpiper"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.5", features = ["derive"] }
flate2 = "1.1.9"
noodles = { version = "0.114.0", features = ["bam", "sam", "bgzf"] }

[profile.release]
opt-level = 3
lto = "thin"
