[package]
name = "bagpiper"
version = "0.2.0"
edition = "2021"
authors = ["Avi Srivastava <avisrilab@gmail.com>"]
description = "A suite of tools for rapid analysis of PIP-seq data."
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/avisrilab/bagpiper"
homepage = "https://github.com/avisrilab/bagpiper"
keywords = ["single-cell", "RNA-seq"]
categories = ["command-line-utilities", "science"]

[lib]
name = "bagpiper"
path = "src/lib.rs"

[[bin]]
name = "bagpiper"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.5", features = ["derive"] }
crossbeam-channel = "0.5.16"
flate2 = "1.1.9"
humantime = "2.4"
log = { version = "0.4", features = ["std"] }
minimap2 = "0.1.31"
needletail = { version = "0.6.3", default-features = false }
noodles = { version = "0.114.0", features = ["bam", "sam", "bgzf"] }
regex = "1.13.1"

[profile.release]
opt-level = 3
lto = "thin"

[dev-dependencies]
bio = "2.3.0"
