//! Count-matrix assembly: per-cell EM over deduped molecules to MatrixMarket + barcodes/features.

use std::collections::BTreeMap;
use std::fs::File;
use std::io::{self, Write};
use std::path::Path;

use flate2::write::GzEncoder;
use flate2::Compression;

use crate::em;
use crate::eqclass::EqClass;

/// Write gzipped `matrix.mtx.gz` (cells x transcripts, MatrixMarket coordinate real general),
/// `barcodes.tsv.gz` (one rendered cell barcode per row), and `features.tsv.gz` (transcript names
/// in reference-id order) into `out_dir`. Molecules must be deduped and cell-sorted (see
/// [`crate::dedup::exact`]) so each run of equal-cell molecules is one matrix row. The declared nnz
/// is the true triplet count.
pub fn write_matrix<P: AsRef<Path>>(eq: &EqClass, out_dir: P) -> io::Result<()> {
    let out_dir = out_dir.as_ref();
    let n_txp = eq.transcripts.len();
    let txp_lengths: Vec<u32> = eq.transcripts.iter().map(|&(_, len)| len).collect();

    let mut barcodes = gz(out_dir.join("barcodes.tsv.gz"))?;
    let mut alphas = vec![0.0f32; n_txp];
    let mut scratch = vec![0.0f32; n_txp];
    let mut triplets: Vec<(u32, u32, f32)> = Vec::new();

    let mols = &eq.molecules;
    let mut row: u32 = 0;
    let mut i = 0;
    while i < mols.len() {
        let cell = mols[i].cell;
        let mut eqmap: BTreeMap<Vec<u32>, u32> = BTreeMap::new();
        while i < mols.len() && mols[i].cell == cell {
            *eqmap.entry(mols[i].txps.clone()).or_insert(0) += 1;
            i += 1;
        }
        row += 1;
        writeln!(barcodes, "{}", cell.render())?;

        alphas.iter_mut().for_each(|a| *a = 0.0);
        em::optimize(&eqmap, &txp_lengths, &mut alphas, &mut scratch);
        for (tid, &alpha) in alphas.iter().enumerate() {
            if alpha > 0.0 {
                triplets.push((row, tid as u32 + 1, alpha));
            }
        }
    }
    barcodes.finish()?;

    let mut mtx = gz(out_dir.join("matrix.mtx.gz"))?;
    writeln!(mtx, "%%MatrixMarket matrix coordinate real general")?;
    writeln!(mtx, "% Generated by bagpiper")?;
    writeln!(mtx, "{}\t{}\t{}", row, n_txp, triplets.len())?;
    for (r, c, v) in &triplets {
        writeln!(mtx, "{}\t{}\t{}", r, c, v)?;
    }
    mtx.finish()?;

    let mut features = gz(out_dir.join("features.tsv.gz"))?;
    for (name, _len) in &eq.transcripts {
        writeln!(features, "{}", name)?;
    }
    features.finish()?;

    Ok(())
}

/// A gzip writer over a new file (deterministic header: flate2 defaults the mtime to 0).
fn gz(path: std::path::PathBuf) -> io::Result<GzEncoder<File>> {
    Ok(GzEncoder::new(File::create(path)?, Compression::default()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::eqclass::Molecule;
    use crate::seq::{CellId, Umi};
    use flate2::read::GzDecoder;
    use std::io::Read;

    fn mol(cb: &str, umi: &str, txps: &[u32]) -> Molecule {
        Molecule {
            cell: CellId::from_ascii(cb.as_bytes()).unwrap(),
            umi: Umi::from_ascii(umi.as_bytes()).unwrap(),
            txps: txps.to_vec(),
        }
    }

    fn read_gz(path: std::path::PathBuf) -> String {
        let mut s = String::new();
        GzDecoder::new(File::open(path).unwrap())
            .read_to_string(&mut s)
            .unwrap();
        s
    }

    #[test]
    fn two_cells_matrix_shape_and_true_nnz() {
        // Cell A: two molecules (one unique TXP0, one shared TXP0/TXP1). Cell B: one unique TXP1.
        // Cells sort by packed barcode; molecules are already dedup-sorted here.
        let eq = EqClass {
            transcripts: vec![("TXP0".to_string(), 100), ("TXP1".to_string(), 100)],
            molecules: vec![
                mol("AAAAAAAAAAAAAAAA", "ACGTACGTACGT", &[0]),
                mol("AAAAAAAAAAAAAAAA", "ACGTACGTACGA", &[0, 1]),
                mol("CAAAAAAAAAAAAAAA", "ACGTACGTACGT", &[1]),
            ],
        };
        let dir = std::env::temp_dir().join(format!("bp_count_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        write_matrix(&eq, &dir).unwrap();

        let barcodes = read_gz(dir.join("barcodes.tsv.gz"));
        assert_eq!(barcodes.lines().count(), 2, "two cells");
        let features = read_gz(dir.join("features.tsv.gz"));
        assert_eq!(features.lines().collect::<Vec<_>>(), vec!["TXP0", "TXP1"]);

        let mtx = read_gz(dir.join("matrix.mtx.gz"));
        let lines: Vec<&str> = mtx.lines().collect();
        assert_eq!(lines[0], "%%MatrixMarket matrix coordinate real general");
        let dims: Vec<&str> = lines[2].split('\t').collect();
        assert_eq!((dims[0], dims[1]), ("2", "2"), "2 cells x 2 transcripts");
        let declared_nnz: usize = dims[2].parse().unwrap();
        assert_eq!(declared_nnz, lines.len() - 3, "declared nnz equals actual triplet lines");

        let _ = std::fs::remove_dir_all(&dir);
    }
}
